### ISSUE TITLE
How to change background color of ProgressHud ?

### ISSUE THREAD

**Issue by tornikegomareli** [redth-org/BTProgressHUD#63] opened 2017-12-07 14:18 UTC
In default my progresshud's background color is white.

How can I change it ?

**Comment by meepou** [comment] 2017-12-26 13:20
Same problem here, background is white, doesn't know how to change it

**Comment by alastor09** [comment] 2018-01-17 04:32
You can use below path to change the background color of HUD
`BigTed.ProgressHUD.Shared.HudBackgroundColour = <YourColor>`

**Comment by michaelmontero** [comment] 2018-03-14 14:31
This issue should be close.

**Comment by darshb** [comment] 2019-09-25 07:25
BigTed.ProgressHUD.Shared.HudBackgroundColour = <YourColor>
Above code not working when application is killed and launched again. Its not showing color which is set for supporting dark mode. Its showing white color only.

**Comment by ChrisMISDB** [comment] 2023-03-02 19:50
Not to resurect a dead thread, but this doesn't work in the new MAUI compatible version.  Is there any update on how to update the HudBackgroundColor and HudForegroundColor?

Thanks!

**Comment by Cheesebaron** [comment] 2023-03-03 09:24
HudForegroundColor is for the text color

Try: `ProgressHUD.Shared.Ring.Color = UIColor.Green`

**Comment by ChrisMISDB** [comment] 2023-03-03 12:18
> 

Thanks, but it isn't the issue of which colors aren't working.  The problem is that 
`ProgressHUD.Shared` doesn't appear to exist in the newest version that's compatible with MAUI

**Comment by Cheesebaron** [comment] 2023-03-06 12:47
OK, I gut the issue now!

So it seems @Redth changed some of this in: https://github.com/redth-org/BTProgressHUD/commit/9a3b340a252659ec9a4085f7ec238254f157576b where he modernized the API.

So instead of calling `ProgressHUD.Shared` you will call `ProgressHUD.For(window)` or `ProgressHUD.ForDefaultWindow()` and then customize the properties on that instance.

Your issue is unrelated to the original issue in this thread. So I will close this one, but feel free to open a new issue explaining in more details what the problem is.

**Closed by Cheesebaron** 2023-03-06 12:47 UTC
